name: Run tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine

    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx vitest run --ci